### ISSUE TITLE
lexpredict-lexnlp install failing

### ISSUE THREAD

**Issue by DeepakSinghRawat** [LexPredict/lexpredict-lexnlp#11]
I am running `pip install -r python-requirements.txt` but it's throwing following error message `16 errors generated.
      error: Command gcc ... failed with exit status 1`. I tried on both osx and ubuntu 16.04. Any pointer to fixing this issue?

**Comment by DomHudson** [comment]
Are you on ubuntu?

`sudo apt install build-essential`

**Comment by ryanmcdonough** [comment]
You need to install the python dev tools

sudo apt-get install python-dev

**Comment by rachhitgarg** [comment]
Failed to build scipy 
Tried both Pip install lexnlp and 
pip install https://github.com/LexPredict/lexpredict-lexnlp/archive/master.zip

**Comment by nayan-mehta** [comment]
Faced the same issue,  3 warnings and 16 errors generated. Any workarounds for this?
