### ISSUE TITLE
AttributeError: type object 'sklearn.tree._criterion.array' has no attribute '__reduce_cython__'

### ISSUE THREAD

**Issue by euribe98** [LexPredict/lexpredict-lexnlp#35]
Hello,
I am evaluating your api and trying to use function get_sections but getting error.  I get this error simply importing. Would you please advise

from lexnlp.nlp.en.segments.sections import get_sections

Same issue 
from lexnlp.nlp.en.segments.titles import get_titles

I've installed dependencies according to:  https://github.com/LexPredict/lexpredict-lexnlp/blob/master/python-requirements-full.txt

**Error**
~/anaconda3/envs/py36/lib/python3.6/site-packages/sklearn/tree/tree.py in <module>
     37 from ..utils.validation import check_is_fitted
     38 
---> 39 from ._criterion import Criterion
     40 from ._splitter import Splitter
     41 from ._tree import DepthFirstTreeBuilder

~/anaconda3/envs/py36/lib/python3.6/site-packages/sklearn/tree/_criterion.cpython-36m-darwin.so in init sklearn.tree._criterion()

AttributeError: type object 'sklearn.tree._criterion.array' has no attribute '__reduce_cython__'

**Dependencies**
[deps.txt](https://github.com/LexPredict/lexpredict-lexnlp/files/4284168/deps.txt)

**Comment by euribe98** [comment]
I resolved this.

**Comment by soflyanna** [comment]
Hello euribe98,
I have the same error. How did you resolve it ?
Tks
